baseURL = "http://rpi.analyticsdojo.com/"
languageCode = "en-us"
title = "Spring 2019 Course Website for Technology Fundamentals for Business Analytics."
theme = "docdock"
publishDir = "docs"
[params]
noHomeIcon = false # default is false
noSearch = false # default is false
showVisitedLinks = false # default is false
# themeStyle = "theme" # overide base css
themeVariant = "blue" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"

[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
pre = "<h3>Important Links</h3>"
name = "<i class='fa fa-github'></i> Course Materials"
url = "https://github.com/rpi-techfundamentals/fall2019-materials"
weight = 1

[[menu.shortcuts]]
name = "<i class='fa fa-cloud'></i> Colab"
url = "http://colab.research.google.com"
weight = 5

[[menu.shortcuts]]
name = "<i class='fa fa-sign-in'></i> LMS"
url = "https://lms.rpi.edu"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-slack'></i>Slack"
identifier = "Slack"
url = "	techfundament-oc98110.slack.com"
weight = 20

[[menu.shortcuts]]
name = "<i class='fa fa-dropbox'></i> Dropbox Share"
identifier = "Dropbox"
url = "https://www.dropbox.com/sh/bnxl5hiyb4fsjbw/AABJuu_Cf207LC8CSf23Sr4ha?dl=0"
weight = 30

[[menu.shortcuts]]
name = "<i class='fa fa-github'></i> Course Website"
url = "https://github.com/AnalyticsDojo/rpi-analyticsdojo-com/"
weight = 40
